# Applications configuration
applications:
  - framework: 'express'
    key: 'express-app'
    session: '[sessions]:default'
    assets: '[assets]:default'
  
  - framework: 'fastify'
    key: 'fastify-app'
    session: '[sessions]:default'
    assets: '[assets]:default'